
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 108
#define YY_END_OF_BUFFER 109
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[339] =
    {   0,
        0,    0,    0,    0,    0,    0,  109,  107,  103,  105,
      104,   69,  107,  107,   86,  107,  107,   77,   78,   59,
       58,   76,   57,   81,   60,   52,   52,   87,   73,   65,
       72,   66,   85,   49,   49,   79,   80,   83,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   74,   84,   75,   82,    6,    7,    6,
        4,    3,    4,    4,  106,    0,   64,    0,  102,    0,
        0,    0,   95,   75,   70,   96,    0,    0,   93,   99,
       91,  100,   92,  101,    0,   55,    5,    9,   94,   56,
       51,    0,   52,   52,    0,   52,   52,   80,   74,   79,

       68,   61,   63,   62,   67,   49,    0,    0,   97,   49,
       49,   49,   49,   49,   49,   49,   44,   49,   49,   49,
       49,   49,   49,   30,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   98,   71,    8,    0,
        0,    0,    0,   53,   88,    0,   55,    9,   55,    0,
       56,   51,   51,   51,    0,   54,   52,   52,   52,   52,
       50,   90,   89,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   47,   49,   49,   23,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,    0,    0,    0,    0,

        0,   55,    0,   55,    0,   56,   51,   51,   51,   51,
       54,   52,   50,   50,   50,   13,   20,   49,   40,   21,
       49,   49,   49,   49,   31,   22,   49,   49,   46,   49,
       49,   24,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   29,   49,   49,    0,    0,    0,
       12,    0,   55,   51,   50,   50,   50,   50,   39,   19,
       49,   49,   49,   49,   41,   49,   49,   49,   49,   49,
       25,   49,   49,   49,   49,   49,   49,   38,   49,   49,
       32,    0,    0,    0,   50,   49,   49,   45,   14,   34,
       48,   49,   49,   33,   27,   36,   15,   28,   37,   49,

       49,   49,    2,    0,    0,   49,   43,   49,   49,   16,
       49,   49,    2,    0,    0,   42,   17,   35,   26,   18,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   11,   10,    0,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,    1,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   23,   24,   25,
       26,   27,   28,    1,   29,   30,   30,   30,   31,   32,
       33,   33,   33,   33,   34,   35,   33,   36,   37,   38,
       33,   39,   40,   33,   41,   33,   42,   43,   33,   33,
       44,   45,   46,   47,   33,    1,   48,   49,   50,   51,

       52,   53,   54,   55,   56,   33,   57,   58,   59,   60,
       61,   62,   33,   63,   64,   65,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[76] =
    {   0,
        1,    2,    3,    1,    1,    2,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        5,    5,    1,    1,    1,    1,    1,    1,    5,    5,
        5,    5,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    1,    1,    1,    5,    5,    5,
        5,    5,    5,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[349] =
    {   0,
        0,    0,   73,   74,   75,   76,  521,  522,  522,  522,
       77,  494,   73,   34,   60,   72,  474,  522,  522,  492,
       75,  522,   76,   78,   89,   86,   91,  490,  522,  110,
      490,   97,  522,    0,  122,  522,  522,  489,  448,   53,
       92,   67,   79,   84,  452,   98,   45,  460,  104,  441,
      450,  448,  453,  522,  105,  522,  522,  522,  522,  487,
      522,  522,  448,  490,  522,  151,  522,  117,  522,    0,
      444,  447,  522,  522,  522,  522,  129,  490,  522,  522,
      522,  522,  522,  522,  482,  144,  522,    0,  522,  159,
      164,  166,  126,  115,    0,  105,  179,  522,  522,  522,

      474,  522,  522,  522,  473,    0,  162,  453,  522,  432,
      435,  443,  430,  445,  432,  438,  424,  425,  422,  422,
      425,  422,  419,    0,  148,  434,  422,  139,  420,  154,
      161,  424,  417,  159,  163,  422,  522,  522,  522,  421,
      442,  425,  414,  522,  522,  211,  522,    0,  217,  225,
      522,  193,  200,  195,  229,  233,  123,  522,  438,  414,
      221,  522,  522,  410,  412,  421,  416,  404,  199,  418,
      416,  412,  404,  410,  413,    0,  399,  403,    0,  406,
      403,  400,  390,  388,  390,  392,  399,  385,  383,  383,
      395,  385,  389,  393,  395,  384,  381,  398,  381,  386,

      245,  250,  262,  522,  252,  267,  235,  522,  402,  378,
      522,  522,  255,  242,  240,    0,    0,  378,    0,    0,
      369,  377,  366,  373,    0,    0,  367,  364,    0,  368,
      369,    0,  362,  362,  361,  358,  370,  360,  364,  369,
      368,  366,  356,  361,    0,  349,  361,  360,  375,  344,
      522,  271,  283,  522,  253,  522,  374,  350,    0,    0,
      347,  348,  353,  344,    0,  351,  379,  336,  344,  339,
        0,  347,  344,  346,  327,  336,  334,    0,  325,  324,
        0,  368,  330,  315,  522,  294,  279,    0,    0,    0,
      522,  291,  292,    0,    0,    0,    0,    0,    0,  287,

      287,  280,    0,  299,  283,  282,    0,  269,  264,    0,
      277,  275,    0,  297,  305,    0,    0,    0,    0,    0,
      285,  308,  303,  298,  257,  241,  276,  238,  290,  213,
      304,  199,  227,  221,  158,  148,  522,  522,  345,  351,
      357,  363,  365,  371,  106,  377,  383,  389
    } ;

static yyconst flex_int16_t yy_def[349] =
    {   0,
      338,    1,  339,  339,  340,  340,  338,  338,  338,  338,
      338,  338,  341,  338,  338,  338,  342,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  343,  343,  338,  338,  338,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  341,  338,  341,
      338,  338,  338,  338,  338,  338,  342,  342,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  344,  338,  338,
      338,  338,  338,  338,  345,  338,  338,  338,  338,  338,

      338,  338,  338,  338,  338,  343,  341,  342,  338,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  344,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      345,  338,  338,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  338,  338,  338,  338,

      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  338,  338,  338,  338,  343,  343,  343,  343,  343,
      338,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  346,  338,  338,  343,  343,  343,  343,  343,
      343,  343,  346,  338,  338,  343,  343,  343,  343,  343,
      338,  338,  347,  348,  338,  347,  347,  348,  348,  338,
      347,  348,  338,  347,  348,  338,  338,    0,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338
    } ;

static yyconst flex_int16_t yy_nxt[598] =
    {   0,
        8,    9,   10,    9,   11,    9,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   34,
       34,   34,   34,   34,   35,   34,   34,   34,   34,   34,
       34,   34,   34,   36,    8,   37,   38,   39,   40,   41,
       42,   43,   44,   45,   34,   46,   34,   47,   34,   34,
       34,   34,   48,   49,   50,   51,   52,   53,   34,   34,
       34,   54,   55,   56,   57,   59,   59,   62,   62,   65,
       69,   66,   75,   63,   63,   73,   74,   60,   60,   71,
       80,   72,  126,   82,   64,   64,   85,   76,   86,   86,

       81,   83,   84,   87,   90,  127,   91,   91,   88,   90,
      161,   97,   97,  111,   89,  112,   92,   70,  116,   99,
       93,   92,  104,  105,   69,   93,   94,  117,   95,  107,
      137,   94,  100,  108,  101,  102,  118,   92,  119,  113,
      144,  121,   92,   96,  122,  158,  114,  120,   96,  159,
      124,   94,  115,   65,   95,   66,   94,  125,  129,  130,
      157,   70,  157,  158,   86,   86,  158,  337,  131,   69,
      158,  132,  160,   78,  146,  147,  329,  138,  147,  149,
      149,  155,   90,  155,   91,   91,  156,  156,  158,  150,
      151,  158,  182,  151,   92,  146,  147,   90,  152,   97,

       97,  147,  183,  184,  153,  178,   70,  186,  188,   92,
      150,  151,  179,   93,  192,   92,  151,  329,  194,   94,
      195,  154,  193,  189,  187,  335,  201,  207,  201,  153,
       92,  202,  202,  208,  209,  208,   96,  149,  149,  327,
      205,  336,  205,  333,   94,  206,  206,  203,  204,  156,
      156,  204,  207,  156,  156,  213,  329,  210,  208,  327,
      208,  214,  221,  222,  211,  202,  202,  211,  203,  204,
      202,  202,  206,  206,  204,  208,  257,  252,  215,  252,
      256,  147,  253,  253,  147,  211,  214,  206,  206,  255,
      211,  253,  253,  256,  327,  256,  330,  255,  151,  258,

      208,  151,  147,  253,  253,  256,  322,  147,  329,  322,
      322,  334,  323,  322,  204,  323,  329,  204,  256,  151,
      256,  327,  327,  325,  151,  321,  320,  319,  318,  324,
      331,  317,  324,  316,  315,  204,  314,  312,  311,  310,
      204,  309,  308,  307,  332,   58,   58,   58,   58,   58,
       58,   61,   61,   61,   61,   61,   61,   68,   68,  306,
       68,   68,   68,   77,   77,  305,  304,   77,   77,  106,
      106,  148,  148,  303,  148,  148,  148,  313,  313,  302,
      313,  313,  313,  326,  301,  300,  326,  326,  326,  328,
      299,  298,  328,  328,  328,  297,  296,  295,  294,  293,

      292,  291,  290,  289,  288,  287,  286,  285,  285,  284,
      283,  282,  281,  280,  279,  278,  277,  276,  275,  274,
      273,  272,  271,  270,  269,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  254,  254,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  224,  223,  220,  219,  218,  217,
      216,  212,  212,  200,  199,  198,  197,  196,  191,  190,
      185,  181,  180,  177,  176,  175,  174,  173,  172,  171,
      170,  169,  168,  167,  166,  165,  164,   78,  163,  162,

      145,   77,  143,  142,  141,  140,  139,  136,  135,  134,
      133,  128,  123,  110,  109,  103,   98,   79,   78,   67,
      338,    7,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338

    } ;

static yyconst flex_int16_t yy_chk[598] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,   11,
       13,   11,   16,    5,    6,   15,   15,    3,    4,   14,
       21,   14,   47,   23,    5,    6,   24,   16,   24,   24,

       21,   23,   23,   25,   26,   47,   26,   26,   25,   27,
      345,   27,   27,   40,   25,   40,   26,   13,   42,   30,
       26,   27,   32,   32,   68,   27,   26,   42,   26,   35,
       55,   27,   30,   35,   30,   30,   43,   26,   43,   41,
       77,   44,   27,   26,   44,   96,   41,   43,   27,   94,
       46,   26,   41,   66,   26,   66,   27,   46,   49,   49,
       93,   68,   96,  157,   86,   86,   93,  336,   49,  107,
       96,   49,   94,   77,   86,   86,  335,   55,   86,   90,
       90,   92,   91,   92,   91,   91,   92,   92,  157,   90,
       90,   93,  128,   90,   91,   86,   86,   97,   91,   97,

       97,   86,  128,  128,   91,  125,  107,  130,  131,   97,
       90,   90,  125,   97,  134,   91,   90,  332,  135,   97,
      135,   91,  134,  131,  130,  332,  146,  152,  146,   91,
       97,  146,  146,  152,  153,  154,   97,  149,  149,  334,
      150,  333,  150,  330,   97,  150,  150,  149,  149,  155,
      155,  149,  154,  156,  156,  161,  328,  153,  152,  326,
      154,  161,  169,  169,  156,  201,  201,  156,  149,  149,
      202,  202,  205,  205,  149,  207,  214,  203,  161,  203,
      215,  202,  203,  203,  202,  156,  161,  206,  206,  213,
      156,  252,  252,  255,  327,  213,  325,  215,  206,  214,

      207,  206,  202,  253,  253,  215,  315,  202,  329,  322,
      315,  331,  315,  322,  253,  322,  324,  253,  255,  206,
      213,  323,  331,  321,  206,  314,  312,  311,  309,  315,
      327,  308,  322,  306,  305,  253,  304,  302,  301,  300,
      253,  293,  292,  287,  329,  339,  339,  339,  339,  339,
      339,  340,  340,  340,  340,  340,  340,  341,  341,  286,
      341,  341,  341,  342,  342,  284,  283,  342,  342,  343,
      343,  344,  344,  282,  344,  344,  344,  346,  346,  280,
      346,  346,  346,  347,  279,  277,  347,  347,  347,  348,
      276,  275,  348,  348,  348,  274,  273,  272,  270,  269,

      268,  267,  266,  264,  263,  262,  261,  258,  257,  250,
      249,  248,  247,  246,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  231,  230,  228,  227,
      224,  223,  222,  221,  218,  210,  209,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      187,  186,  185,  184,  183,  182,  181,  180,  178,  177,
      175,  174,  173,  172,  171,  170,  168,  167,  166,  165,
      164,  160,  159,  143,  142,  141,  140,  136,  133,  132,
      129,  127,  126,  123,  122,  121,  120,  119,  118,  117,
      116,  115,  114,  113,  112,  111,  110,  108,  105,  101,

       85,   78,   72,   71,   64,   63,   60,   53,   52,   51,
       50,   48,   45,   39,   38,   31,   28,   20,   17,   12,
        7,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338,  338,  338,  338,
      338,  338,  338,  338,  338,  338,  338

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "vcp_lex.l"
#line 9 "vcp_lex.l"


#include "program_struct.h"

#include "vcp_yacc.h"



static string str_tmp="";//store the content of the comment

static int line_begin=0;//store the beginning line of the comment

static int line_end=0;//store the ending line of the comment



//2010年3月10日追加

static bool line=false;//一个开关，标记当前是否位于#line后面



//defined in file : ./parser_utils.c

extern bool enter_noparse;

extern list<string>* type_names;

extern void store_cmnts(Cmnt*);

extern int check_type(string,list<string>*);

extern void yyerror(string err_info);



//defined in file : src/main_utils.c

extern int line_num;

extern list<Cmnt>* cmnts;

extern int str2int(string);

extern string int2str(int);



//2010年3月10日追加

extern string file_info;

extern int fake_line_num;



#define TRANSFER  char* dup_str = strdup(yytext); yylval.text = dup_str;





#line 730 "lex.yy.c"

#define INITIAL 0
#define CMNT 1
#define NOPARSE 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 45 "vcp_lex.l"

#line 943 "lex.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 339 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 522 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 46 "vcp_lex.l"
{ 	BEGIN INITIAL;

								enter_noparse=false;

								str_tmp+="/*KWNOPARSE*/";

								str_tmp="/*KWNOPARSE*/"+str_tmp;

								line_begin=cmnts->back().get_line_begin();

								line_end=fake_line_num;

								Cmnt* cmnt=new Cmnt(str_tmp,line_begin,line_end);

								line_begin=0;

								line_end=0;

								cmnts->pop_back();

								cmnts->push_back(*cmnt);str_tmp="";

							}

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "vcp_lex.l"
{}

	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 59 "vcp_lex.l"
{line_num++;fake_line_num++;str_tmp+="\n";}

	YY_BREAK
case 4:
YY_RULE_SETUP
#line 61 "vcp_lex.l"
{str_tmp+=(string)yytext;}

	YY_BREAK
case 5:
YY_RULE_SETUP
#line 66 "vcp_lex.l"
{line_begin=fake_line_num;str_tmp+="/*";BEGIN CMNT;}

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 68 "vcp_lex.l"
{str_tmp+=(string)yytext;}

	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 70 "vcp_lex.l"
{line_num++;fake_line_num++;str_tmp+="\n";}

	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "vcp_lex.l"
{	line_end=fake_line_num;

					BEGIN INITIAL;

					str_tmp+="*/";

					Cmnt* cmnt=new Cmnt(str_tmp,line_begin,line_end);



					line_begin=0;line_end=0;

					store_cmnts(cmnt);

					str_tmp="";

					if(enter_noparse==true)

					{

						BEGIN NOPARSE;

					}

				}

	YY_BREAK
case 9:
YY_RULE_SETUP
#line 88 "vcp_lex.l"
{yyerror("\"//\" is not supported!"); }

	YY_BREAK
case 10:
YY_RULE_SETUP
#line 92 "vcp_lex.l"
{TRANSFER   return(INCLUDE);}

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "vcp_lex.l"
{TRANSFER   return(INCLUDE);}

	YY_BREAK
case 12:
YY_RULE_SETUP
#line 96 "vcp_lex.l"
{line=true;}

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 99 "vcp_lex.l"
{ return(AUTO); }

	YY_BREAK
case 14:
YY_RULE_SETUP
#line 100 "vcp_lex.l"
{ return(EXTERN); }

	YY_BREAK
case 15:
YY_RULE_SETUP
#line 101 "vcp_lex.l"
{ cout<<"warning : using \"static\" keyword! on line "<<line_num<<" of file : "<<file_info<<endl; return(STATIC);}

	YY_BREAK
case 16:
YY_RULE_SETUP
#line 102 "vcp_lex.l"
{ return(TYPEDEF); }

	YY_BREAK
case 17:
YY_RULE_SETUP
#line 103 "vcp_lex.l"
{ cout<<"warning : using \"register\" keyword! on line "<<line_num<<" of file : "<<file_info<<endl; return(REGISTER); }

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 105 "vcp_lex.l"
{cout<<"warning : using \"volatile\" keyword! on line "<<line_num<<" of file : "<<file_info<<endl; return(VOLATILE);  }

	YY_BREAK
case 19:
YY_RULE_SETUP
#line 106 "vcp_lex.l"
{ cout<<"warning : using \"const\" keyword! on line "<<line_num<<" of file : "<<file_info<<endl; return(CONST);  }

	YY_BREAK
case 20:
YY_RULE_SETUP
#line 107 "vcp_lex.l"
{ return(BOOL); }

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 108 "vcp_lex.l"
{ yyerror("keyword char is not supported!"); }

	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "vcp_lex.l"
{ return(ENUM); }

	YY_BREAK
case 23:
YY_RULE_SETUP
#line 110 "vcp_lex.l"
{ return(INT); }

	YY_BREAK
case 24:
YY_RULE_SETUP
#line 111 "vcp_lex.l"
{ return(LONG); }

	YY_BREAK
case 25:
YY_RULE_SETUP
#line 112 "vcp_lex.l"
{yyerror("keyword short is not supported!");  }

	YY_BREAK
case 26:
YY_RULE_SETUP
#line 113 "vcp_lex.l"
{ return(UNSIGNED); }

	YY_BREAK
case 27:
YY_RULE_SETUP
#line 114 "vcp_lex.l"
{ return(SIGNED); }

	YY_BREAK
case 28:
YY_RULE_SETUP
#line 115 "vcp_lex.l"
{ return(STRUCT); }

	YY_BREAK
case 29:
YY_RULE_SETUP
#line 116 "vcp_lex.l"
{ return(VOID); }

	YY_BREAK
case 30:
YY_RULE_SETUP
#line 118 "vcp_lex.l"
{ return(IF); }

	YY_BREAK
case 31:
YY_RULE_SETUP
#line 119 "vcp_lex.l"
{ return(ELSE); }

	YY_BREAK
case 32:
YY_RULE_SETUP
#line 121 "vcp_lex.l"
{ return(WHILE); }

	YY_BREAK
case 33:
YY_RULE_SETUP
#line 123 "vcp_lex.l"
{ return(RETURN); }

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 127 "vcp_lex.l"
{ yyerror("keyword inline is not supported!"); }

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 128 "vcp_lex.l"
{ yyerror("keyword restrict is not supported!"); }

	YY_BREAK
case 36:
YY_RULE_SETUP
#line 129 "vcp_lex.l"
{ yyerror("keyword sizeof is not supported!"); }

	YY_BREAK
case 37:
YY_RULE_SETUP
#line 130 "vcp_lex.l"
{ yyerror("keyword switch is not supported!"); }

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 131 "vcp_lex.l"
{ yyerror("keyword union is not supported!"); }

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 132 "vcp_lex.l"
{ yyerror("keyword break is not supported!"); }

	YY_BREAK
case 40:
YY_RULE_SETUP
#line 133 "vcp_lex.l"
{ yyerror("keyword case is not supported!"); }

	YY_BREAK
case 41:
YY_RULE_SETUP
#line 134 "vcp_lex.l"
{ yyerror("keyword float is not supported!"); }

	YY_BREAK
case 42:
YY_RULE_SETUP
#line 135 "vcp_lex.l"
{ yyerror("keyword continue is not supported!"); }

	YY_BREAK
case 43:
YY_RULE_SETUP
#line 136 "vcp_lex.l"
{ yyerror("keyword default is not supported!"); }

	YY_BREAK
case 44:
YY_RULE_SETUP
#line 137 "vcp_lex.l"
{ yyerror("keyword do is not supported!"); }

	YY_BREAK
case 45:
YY_RULE_SETUP
#line 138 "vcp_lex.l"
{ yyerror("keyword double is not supported!"); }

	YY_BREAK
case 46:
YY_RULE_SETUP
#line 139 "vcp_lex.l"
{ yyerror("keyword goto is not supported!"); }

	YY_BREAK
case 47:
YY_RULE_SETUP
#line 140 "vcp_lex.l"
{ yyerror("keyword for is not supported!"); }

	YY_BREAK
case 48:
YY_RULE_SETUP
#line 141 "vcp_lex.l"
{ yyerror("keyword label is not supported!"); }

	YY_BREAK
case 49:
YY_RULE_SETUP
#line 145 "vcp_lex.l"
{ TRANSFER; return(check_type(yytext,type_names)); }

	YY_BREAK
case 50:
YY_RULE_SETUP
#line 147 "vcp_lex.l"
{ string temp=yytext; int temp1=str2int(temp);yylval.text=(char*)(int2str(temp1).c_str()); return(CONSTANT); }

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 148 "vcp_lex.l"
{ string temp=yytext; int temp1=str2int(temp);yylval.text=(char*)(int2str(temp1).c_str()); return(CONSTANT);}

	YY_BREAK
case 52:
YY_RULE_SETUP
#line 151 "vcp_lex.l"
{if(true==line){string temp=yytext; line_num=str2int(temp);line_num--;}else{TRANSFER; return(CONSTANT);} }

	YY_BREAK
case 53:
YY_RULE_SETUP
#line 153 "vcp_lex.l"
{ yyerror("character is not supported!");  }

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 154 "vcp_lex.l"
{ TRANSFER; return(CONSTANT); }

	YY_BREAK
case 55:
YY_RULE_SETUP
#line 155 "vcp_lex.l"
{ yyerror("decimal is not supported!"); }

	YY_BREAK
case 56:
YY_RULE_SETUP
#line 156 "vcp_lex.l"
{ yyerror("decimal is not supported!"); }

	YY_BREAK
case 57:
YY_RULE_SETUP
#line 159 "vcp_lex.l"
{  return(SUB); }

	YY_BREAK
case 58:
YY_RULE_SETUP
#line 160 "vcp_lex.l"
{  return(ADD); }

	YY_BREAK
case 59:
YY_RULE_SETUP
#line 161 "vcp_lex.l"
{  return(MUL); }

	YY_BREAK
case 60:
YY_RULE_SETUP
#line 162 "vcp_lex.l"
{  return(DIV); }

	YY_BREAK
case 61:
YY_RULE_SETUP
#line 163 "vcp_lex.l"
{  return(LE); }

	YY_BREAK
case 62:
YY_RULE_SETUP
#line 164 "vcp_lex.l"
{  return(GE); }

	YY_BREAK
case 63:
YY_RULE_SETUP
#line 165 "vcp_lex.l"
{  return(EQ); }

	YY_BREAK
case 64:
YY_RULE_SETUP
#line 166 "vcp_lex.l"
{  return(NE); }

	YY_BREAK
case 65:
YY_RULE_SETUP
#line 167 "vcp_lex.l"
{  return(LT); }

	YY_BREAK
case 66:
YY_RULE_SETUP
#line 168 "vcp_lex.l"
{  return(GT); }

	YY_BREAK
case 67:
YY_RULE_SETUP
#line 169 "vcp_lex.l"
{  return(RIGHT); }

	YY_BREAK
case 68:
YY_RULE_SETUP
#line 170 "vcp_lex.l"
{  return(LEFT); }

	YY_BREAK
case 69:
YY_RULE_SETUP
#line 171 "vcp_lex.l"
{  return(NOT); }

	YY_BREAK
case 70:
YY_RULE_SETUP
#line 172 "vcp_lex.l"
{  return(AND); }

	YY_BREAK
case 71:
YY_RULE_SETUP
#line 173 "vcp_lex.l"
{  return(OR); }

	YY_BREAK
case 72:
YY_RULE_SETUP
#line 174 "vcp_lex.l"
{  return('='); }

	YY_BREAK
case 73:
YY_RULE_SETUP
#line 175 "vcp_lex.l"
{  return(';'); }

	YY_BREAK
case 74:
YY_RULE_SETUP
#line 176 "vcp_lex.l"
{  return('{'); }

	YY_BREAK
case 75:
YY_RULE_SETUP
#line 177 "vcp_lex.l"
{  return('}'); }

	YY_BREAK
case 76:
YY_RULE_SETUP
#line 178 "vcp_lex.l"
{  return(','); }

	YY_BREAK
case 77:
YY_RULE_SETUP
#line 179 "vcp_lex.l"
{  return('('); }

	YY_BREAK
case 78:
YY_RULE_SETUP
#line 180 "vcp_lex.l"
{  return(')'); }

	YY_BREAK
case 79:
YY_RULE_SETUP
#line 181 "vcp_lex.l"
{  return('['); }

	YY_BREAK
case 80:
YY_RULE_SETUP
#line 182 "vcp_lex.l"
{  return(']'); }

	YY_BREAK
case 81:
YY_RULE_SETUP
#line 183 "vcp_lex.l"
{  return('.'); }

	YY_BREAK
case 82:
YY_RULE_SETUP
#line 184 "vcp_lex.l"
{ return(BitNot); }

	YY_BREAK
case 83:
YY_RULE_SETUP
#line 187 "vcp_lex.l"
{  yyerror("\'^\' is not supported!"); }

	YY_BREAK
case 84:
YY_RULE_SETUP
#line 188 "vcp_lex.l"
{  yyerror("\'|\' is not supported!"); }

	YY_BREAK
case 85:
YY_RULE_SETUP
#line 189 "vcp_lex.l"
{  yyerror("\'\?\' is not supported!"); }

	YY_BREAK
case 86:
YY_RULE_SETUP
#line 190 "vcp_lex.l"
{  yyerror("\'%\' is not supported!"); }

	YY_BREAK
case 87:
YY_RULE_SETUP
#line 191 "vcp_lex.l"
{  yyerror("位域\':\' is not supported!"); }

	YY_BREAK
case 88:
YY_RULE_SETUP
#line 192 "vcp_lex.l"
{  yyerror("\'...\' is not supported!"); }

	YY_BREAK
case 89:
YY_RULE_SETUP
#line 193 "vcp_lex.l"
{  yyerror("\'>>=\' is not supported!"); }

	YY_BREAK
case 90:
YY_RULE_SETUP
#line 194 "vcp_lex.l"
{  yyerror("\'<<=\' is not supported!"); }

	YY_BREAK
case 91:
YY_RULE_SETUP
#line 195 "vcp_lex.l"
{  yyerror("\'+=\' is not supported!"); }

	YY_BREAK
case 92:
YY_RULE_SETUP
#line 196 "vcp_lex.l"
{  yyerror("\'-=\' is not supported!"); }

	YY_BREAK
case 93:
YY_RULE_SETUP
#line 197 "vcp_lex.l"
{  yyerror("\'*=\' is not supported!"); }

	YY_BREAK
case 94:
YY_RULE_SETUP
#line 198 "vcp_lex.l"
{  yyerror("\'/=\' is not supported!"); }

	YY_BREAK
case 95:
YY_RULE_SETUP
#line 199 "vcp_lex.l"
{  yyerror("\'%=\' is not supported!"); }

	YY_BREAK
case 96:
YY_RULE_SETUP
#line 200 "vcp_lex.l"
{  yyerror("\'&=\' is not supported!"); }

	YY_BREAK
case 97:
YY_RULE_SETUP
#line 201 "vcp_lex.l"
{  yyerror("\'^=\' is not supported!"); }

	YY_BREAK
case 98:
YY_RULE_SETUP
#line 202 "vcp_lex.l"
{  yyerror("\'|=\' is not supported!"); }

	YY_BREAK
case 99:
YY_RULE_SETUP
#line 203 "vcp_lex.l"
{  yyerror("\'++\' is not supported!"); }

	YY_BREAK
case 100:
YY_RULE_SETUP
#line 204 "vcp_lex.l"
{  yyerror("\'--\' is not supported!"); }

	YY_BREAK
case 101:
YY_RULE_SETUP
#line 205 "vcp_lex.l"
{  yyerror("\'->\' is not supported!"); }

	YY_BREAK
case 102:
YY_RULE_SETUP
#line 206 "vcp_lex.l"
{  if(true==line){file_info=yytext;line=false;}else{yyerror("string is not supported!");} }

	YY_BREAK
case 103:
YY_RULE_SETUP
#line 208 "vcp_lex.l"
{;}

	YY_BREAK
case 104:
#line 210 "vcp_lex.l"
case 105:
/* rule 105 can match eol */
#line 211 "vcp_lex.l"
case 106:
/* rule 106 can match eol */
YY_RULE_SETUP
#line 211 "vcp_lex.l"
{ line_num++;fake_line_num++;}

	YY_BREAK
case 107:
YY_RULE_SETUP
#line 212 "vcp_lex.l"
{  yyerror("invalid characters!"); }

	YY_BREAK
case 108:
YY_RULE_SETUP
#line 214 "vcp_lex.l"
ECHO;
	YY_BREAK
#line 1561 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CMNT):
case YY_STATE_EOF(NOPARSE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 339 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 339 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 338);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;

    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;

	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;

	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;

	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;

	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 *
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{

	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 *
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 *
 */
int yyget_lineno  (void)
{

    return yylineno;
}

/** Get the input stream.
 *
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 *
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 *
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 *
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 *
 */
void yyset_lineno (int  line_number )
{

    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 *
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 214 "vcp_lex.l"




int yywrap(void)

{

	return 1;

}
















